#!/bin/sh

echo "meta-k230 initramfs starting..."

mkdir -p /proc /sys /dev
mount -t proc none /proc || echo "WARNING: mount /proc failed"
mount -t sysfs none /sys || echo "WARNING: mount /sys failed"
mount -t devtmpfs none /dev || echo "WARNING: mount /dev failed"

if [ -e /dev/console ]; then
    exec </dev/console >/dev/console 2>&1
fi

echo "Dropping to shell..."
exec /bin/sh
