BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
              ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "k230"
BBFILE_PATTERN_k230 = "^${LAYERDIR}/"
BBFILE_PRIORITY_k230 = "6"

LAYERDEPENDS_k230 = "riscv-layer"
LAYERSERIES_COMPAT_k230 = "scarthgap"
